version: '3'
services:
  app:
    image: 'strawberry-player'
    build: '.'
    expose:
      # Websockets
      - 10000
    ports:
      - 4200:80
    sysctls:
      # Weird asyncio behavior with ipv6 enabled
      - net.ipv6.conf.all.disable_ipv6=1
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
